Document: afflib
Title: Debian afflib Manual
Author: <insert document author here>
Abstract: This manual describes what afflib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/afflib/afflib.sgml.gz

Format: postscript
Files: /usr/share/doc/afflib/afflib.ps.gz

Format: text
Files: /usr/share/doc/afflib/afflib.text.gz

Format: HTML
Index: /usr/share/doc/afflib/html/index.html
Files: /usr/share/doc/afflib/html/*.html

  
